version: "3.8"
x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "1"
  driver: json-file
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    command: mysqld --sql_mode='NO_ENGINE_SUBSTITUTION'
    restart: on-failure
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - /var/volumes/mysql:/var/lib/mysql
    logging: *default-logging
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: supply-store
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    logging: *default-logging
networks:
  default:
    name: supply-store
    driver: bridge
